# Generated by Django 6.0.4 on 2026-04-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fila', models.CharField(max_length=10)),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'asiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoEvento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_evento', models.DateField()),
                ('hora_evento', models.TimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventoAsiento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'evento_asiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventoZona',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidad_evento', models.IntegerField(blank=True, null=True)),
                ('nombre_display', models.CharField(blank=True, max_length=100, null=True)),
                ('limite_por_usuario', models.IntegerField()),
                ('habilitada', models.BooleanField()),
            ],
            options={
                'db_table': 'evento_zona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FasePrecio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('habilitada', models.BooleanField()),
            ],
            options={
                'db_table': 'fase_precio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FasePrecioZona',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'fase_precio_zona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo_zona', models.CharField(max_length=10)),
                ('tipo_asignacion', models.CharField(max_length=10)),
                ('codigo_color', models.CharField(blank=True, max_length=20, null=True)),
                ('capacidad_base', models.IntegerField(blank=True, null=True)),
                ('orden_visual', models.IntegerField()),
            ],
            options={
                'db_table': 'zona',
                'managed': False,
            },
        ),
    ]
