# Generated by Django 6.0.4 on 2026-04-23 20:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_evento',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo_zona', models.CharField(max_length=10)),
                ('tipo_asignacion', models.CharField(max_length=10)),
                ('codigo_color', models.CharField(blank=True, max_length=20, null=True)),
                ('capacidad_base', models.IntegerField(blank=True, null=True)),
                ('orden_visual', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'zona',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3)])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_evento', models.DateField()),
                ('hora_evento', models.TimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='events.estadoevento')),
            ],
            options={
                'db_table': 'evento',
                'ordering': ['-fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='EventoZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidad_evento', models.IntegerField(blank=True, null=True)),
                ('nombre_display', models.CharField(blank=True, max_length=100, null=True)),
                ('limite_por_usuario', models.IntegerField(default=4)),
                ('habilitada', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.evento')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.zona')),
            ],
            options={
                'db_table': 'evento_zona',
                'unique_together': {('evento', 'zona')},
            },
        ),
        migrations.CreateModel(
            name='FasePrecio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('habilitada', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases_precio', to='events.evento')),
            ],
            options={
                'db_table': 'fase_precio',
                'ordering': ['orden'],
                'managed': True,
                'unique_together': {('evento', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(max_length=10)),
                ('numero', models.IntegerField()),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.zona')),
            ],
            options={
                'db_table': 'asiento',
                'unique_together': {('zona', 'fila', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='EventoAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('BLOQUEADO', 'Bloqueado'), ('VENDIDO', 'Vendido')], default='DISPONIBLE', max_length=15)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.asiento')),
                ('evento_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventozona')),
            ],
            options={
                'db_table': 'evento_asiento',
                'unique_together': {('evento_zona', 'asiento')},
            },
        ),
        migrations.CreateModel(
            name='FasePrecioZona',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('evento_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases_precio', to='events.eventozona')),
                ('fase_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_zona', to='events.faseprecio')),
            ],
            options={
                'db_table': 'fase_precio_zona',
                'managed': True,
                'unique_together': {('fase_precio', 'evento_zona')},
            },
        ),
    ]
