# Generated by Django 6.0.4 on 2026-04-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asiento',
            options={'managed': False, 'verbose_name': 'Asiento Físico', 'verbose_name_plural': 'Asientos Físicos'},
        ),
        migrations.AlterModelOptions(
            name='estadoevento',
            options={'managed': False, 'verbose_name': 'Estado de Evento', 'verbose_name_plural': 'Estados de Evento'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'managed': False, 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='eventoasiento',
            options={'managed': False, 'verbose_name': 'Estado de Asiento por Evento', 'verbose_name_plural': 'Estados de Asientos por Evento'},
        ),
        migrations.AlterModelOptions(
            name='eventozona',
            options={'managed': False, 'verbose_name': 'Configuración de Zona por Evento', 'verbose_name_plural': 'Configuraciones de Zonas por Evento'},
        ),
        migrations.AlterModelOptions(
            name='faseprecio',
            options={'managed': False, 'verbose_name': 'Fase de Precio', 'verbose_name_plural': 'Fases de Precios'},
        ),
        migrations.AlterModelOptions(
            name='fasepreciozona',
            options={'managed': False, 'verbose_name': 'Precio de Fase por Zona', 'verbose_name_plural': 'Precios de Fases por Zonas'},
        ),
        migrations.AlterModelOptions(
            name='zona',
            options={'managed': False, 'verbose_name': 'Zona Física', 'verbose_name_plural': 'Zonas Físicas'},
        ),
    ]
