# Generated by Django 6.0.4 on 2026-04-23 20:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('activa', 'Activa'), ('confirmada', 'Confirmada'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada')], db_index=True, max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_reserva',
                'db_table_comment': 'activa | confirmada | expirada | cancelada',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_reserva', models.CharField(db_index=True, max_length=30, unique=True)),
                ('total_reserva', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reserva',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('evento_asiento', models.ForeignKey(blank=True, db_comment='NULL para General/Fosa. NOT NULL para VIP', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_reserva', to='events.eventoasiento')),
                ('evento_zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_reserva', to='events.eventozona')),
            ],
            options={
                'db_table': 'detalle_reserva',
                'managed': True,
            },
        ),
    ]
