# Generated by Django 6.0.4 on 2026-04-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_comment='VIP = siempre 1. General/Fosa = numero de personas')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'detalle_reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_reserva',
                'db_table_comment': 'activa | confirmada | expirada | cancelada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_reserva', models.CharField(max_length=30, unique=True)),
                ('total_reserva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_expiracion', models.DateTimeField(blank=True, db_comment='NULL en ventanilla. Web: now() + intervalo configurado (ej: 15 min)', null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
    ]
