# Generated by Django 6.0.4 on 2026-04-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalVenta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Canal de Venta',
                'verbose_name_plural': 'Canales de Venta',
                'db_table': 'canal_venta',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='detallereserva',
            options={'managed': False, 'verbose_name': 'Detalle de la Reserva', 'verbose_name_plural': 'Detalles de las Reservas'},
        ),
        migrations.AlterModelOptions(
            name='estadoreserva',
            options={'managed': False, 'verbose_name': 'Estado de Reserva', 'verbose_name_plural': 'Estados de Reserva'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'managed': False, 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
    ]
