# Generated by Django 6.0.4 on 2026-04-23 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('reservations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='creada_por_usuario',
            field=models.ForeignKey(db_comment='Cliente o empleado que genera la reserva', on_delete=django.db.models.deletion.PROTECT, related_name='reservas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservations.estadoreserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='events.evento'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fase_precio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='events.faseprecio'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(blank=True, db_comment='NULL permitido para ventas en ventanilla', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallereserva',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='reservations.reserva'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['evento', 'estado_reserva'], name='reserva_evento__c593a4_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_expiracion'], name='reserva_fecha_e_73107c_idx'),
        ),
        migrations.AddIndex(
            model_name='detallereserva',
            index=models.Index(fields=['reserva'], name='detalle_res_reserva_731fa1_idx'),
        ),
        migrations.AddConstraint(
            model_name='detallereserva',
            constraint=models.UniqueConstraint(condition=models.Q(('evento_asiento__isnull', False)), fields=('evento_asiento',), name='unique_evento_asiento_reserva'),
        ),
    ]
