# Generated by Django 6.0.4 on 2026-04-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalVenta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'canal_venta',
                'db_table_comment': 'web | ventanilla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPago',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_pago',
                'db_table_comment': 'pendiente | pagado | rechazado | reembolsado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoVenta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_venta',
                'db_table_comment': 'emitida | anulada | reembolsada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'metodo_pago',
                'db_table_comment': 'transferencia_qr | tarjeta_visa | efectivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaccion_interna', models.UUIDField(db_comment='UUID unico del sistema. Usar como idempotency_key para webhooks', unique=True)),
                ('referencia_externa', models.CharField(blank=True, db_comment='Codigo de transaccion del banco boliviano (viene en el webhook)', max_length=200, null=True)),
                ('comprobante_url', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_dato', models.TextField(blank=True, null=True)),
                ('qr_imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateTimeField()),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
    ]
