# Generated by Django 6.0.4 on 2026-04-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadopago',
            options={'managed': False, 'verbose_name': 'Estado de Pago', 'verbose_name_plural': 'Estados de Pago'},
        ),
        migrations.AlterModelOptions(
            name='metodopago',
            options={'managed': False, 'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'managed': False, 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
    ]
