# Generated by Django 6.0.4 on 2026-04-23 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('reservations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='confirmado_por_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_confirmados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='estado_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='payments.estadopago'),
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='payments.metodopago'),
        ),
        migrations.AddField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='reservations.reserva'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estado_pago', 'fecha_creacion'], name='pago_estado__7b54d2_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['referencia_externa'], name='pago_referen_fc19e5_idx'),
        ),
    ]
