# Generated by Django 6.0.4 on 2026-05-17 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPagoGuardado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ultimos_cuatro', models.CharField(max_length=4)),
                ('marca', models.CharField(max_length=50)),
                ('fecha_expiracion', models.CharField(max_length=7)),
                ('token_simulado', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago_guardados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'metodo_pago_guardado',
                'ordering': ['-creado_en'],
                'managed': True,
            },
        ),
    ]
