# Generated by Django 6.0.4 on 2026-06-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_metodopagoguardado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoPayPalPendiente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('paypal_payment_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('usuario_id', models.IntegerField()),
                ('evento_id', models.IntegerField()),
                ('carrito_data', models.JSONField()),
                ('monto_bs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('procesado', 'Procesado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
            ],
            options={
                'db_table': 'pago_paypal_pendiente',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
