# Generated by Django 6.0.4 on 2026-04-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'rol',
                'db_table_comment': 'Roles del sistema: administrador, cliente, empleado, soporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.TextField(db_comment='CITEXT: busquedas case-insensitive sin lower()', unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('contrasena_hash', models.CharField(db_comment='Hash bcrypt/argon2  nunca texto plano', max_length=255)),
                ('activo', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
