# Generated by Django 6.0.4 on 2026-04-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
