# Generated by Django 6.0.4 on 2026-04-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False, 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
