# Generated by Django 6.0.4 on 2026-05-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_notif_eventos_usuario_notif_promociones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
