# Generated by Django 6.0.4 on 2026-05-17 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_notif_eventos_usuario_notif_promociones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='SesionDispositivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('navegador', models.CharField(blank=True, max_length=255, null=True)),
                ('sistema_operativo', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_dispositivo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sesion_dispositivo',
                'ordering': ['-ultimo_acceso'],
                'managed': True,
            },
        ),
    ]
