# Generated by Django 6.0.4 on 2026-05-26 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_admin_notif_configuracionsistema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionsistema',
            options={'managed': True, 'verbose_name': 'Configuración del Sistema', 'verbose_name_plural': 'Configuraciones del Sistema'},
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='reserva_bloqueo_minutos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='admin_notif_reportes',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='admin_notif_reservas',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='admin_notif_soporte',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='admin_notif_ventas',
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='soporte_humano_habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='soporte_humano_hora_fin',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='soporte_humano_hora_inicio',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
