# Generated by Django 6.0.4 on 2026-05-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usuario_admin_notif_reportes_and_more'),
        ('users', '0006_alter_configuracionsistema_options_and_more'),
    ]

    operations = [
    ]
