# Generated by Django 6.0.4 on 2026-06-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_configuracionsistema_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='admin_notif_reservas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='admin_notif_ventas',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
