# Generated by Django 6.0.4 on 2026-06-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usuario_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='admin_notif_reservas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='admin_notif_ventas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='admin_notif_soporte',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='admin_notif_reportes',
            field=models.BooleanField(default=False),
        ),
    ]
