# Generated by Django 6.0.4 on 2026-04-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_ticket', models.UUIDField(unique=True)),
                ('codigo_qr', models.CharField(db_comment='Contenido del QR escaneado en el acceso. Puede ser UUID o HMAC firmado', max_length=255, unique=True)),
                ('descripcion_ubicacion', models.CharField(max_length=150)),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usada', models.BooleanField()),
                ('fecha_emision', models.DateTimeField()),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entrada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoEntrada',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_entrada',
                'db_table_comment': 'emitida | usada | cancelada',
                'managed': False,
            },
        ),
    ]
