# Generated by Django 6.0.4 on 2026-04-23 20:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalVenta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('web', 'Web'), ('ventanilla', 'Ventanilla')], db_index=True, max_length=50, unique=True)),
            ],
            options={
                'db_table': 'canal_venta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoEntrada',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('emitida', 'Emitida'), ('usada', 'Usada'), ('cancelada', 'Cancelada')], db_index=True, max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_entrada',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoVenta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('emitida', 'Emitida'), ('anulada', 'Anulada'), ('reembolsada', 'Reembolsada')], db_index=True, max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_venta',
                'db_table_comment': 'emitida | anulada | reembolsada',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'venta',
                'ordering': ['-fecha_venta'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_ticket', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('codigo_qr', models.CharField(db_comment='Contenido QR (ideal: HMAC firmado)', db_index=True, max_length=255, unique=True)),
                ('descripcion_ubicacion', models.CharField(max_length=150)),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('usada', models.BooleanField(db_index=True, default=False)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('detalle_reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='reservations.detallereserva')),
            ],
            options={
                'db_table': 'entrada',
                'managed': True,
            },
        ),
    ]
