# Generated by Django 6.0.4 on 2026-04-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrada',
            options={'managed': False, 'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
        migrations.AlterModelOptions(
            name='estadoentrada',
            options={'managed': False, 'verbose_name': 'Estado de Entrada', 'verbose_name_plural': 'Estados de Entrada'},
        ),
    ]
