# Generated by Django 6.0.4 on 2026-04-23 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0003_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='validado_por_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_validadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrada',
            name='estado_entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='tickets.estadoentrada'),
        ),
        migrations.AddField(
            model_name='venta',
            name='canal_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='tickets.canalventa'),
        ),
        migrations.AddField(
            model_name='venta',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='tickets.estadoventa'),
        ),
        migrations.AddField(
            model_name='venta',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='venta', to='reservations.reserva'),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrada',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='tickets.venta'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado_venta', 'fecha_venta'], name='venta_estado__8d5d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['codigo_qr'], name='entrada_codigo__1c3102_idx'),
        ),
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['usada', 'estado_entrada'], name='entrada_usada_8cc114_idx'),
        ),
    ]
