# Generated by Django 6.0.4 on 2026-04-23 20:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSoporte',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('pago', 'Pago'), ('entrada', 'Entrada'), ('reembolso', 'Reembolso'), ('otro', 'Otro')], max_length=50, unique=True)),
            ],
            options={
                'db_table': 'categoria_soporte',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoSoporte',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('cerrado', 'Cerrado')], db_index=True, max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_soporte',
                'db_table_comment': 'abierto | en_proceso | cerrado',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SoporteMensaje',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'soporte_mensaje',
                'ordering': ['fecha_envio'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_reclamo', models.CharField(db_index=True, max_length=30, unique=True)),
                ('asunto', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(5)])),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria_soporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='support.categoriasoporte')),
            ],
            options={
                'db_table': 'soporte',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
    ]
