# Generated by Django 6.0.4 on 2026-04-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSoporte',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'categoria_soporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoSoporte',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_soporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_reclamo', models.CharField(max_length=30, unique=True)),
                ('asunto', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'soporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoporteMensaje',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField()),
            ],
            options={
                'db_table': 'soporte_mensaje',
                'managed': False,
            },
        ),
    ]
