# Generated by Django 6.0.4 on 2026-04-23 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('support', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporte',
            name='entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soportes', to='tickets.entrada'),
        ),
        migrations.AddField(
            model_name='soporte',
            name='estado_soporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='support.estadosoporte'),
        ),
        migrations.AddField(
            model_name='soporte',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soportes', to='payments.pago'),
        ),
    ]
