# Generated by Django 6.0.4 on 2026-04-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriasoporte',
            options={'managed': False, 'verbose_name': 'Categoría de Soporte', 'verbose_name_plural': 'Categorías de Soporte'},
        ),
        migrations.AlterModelOptions(
            name='estadosoporte',
            options={'managed': False, 'verbose_name': 'Estado de Soporte', 'verbose_name_plural': 'Estados de Soporte'},
        ),
        migrations.AlterModelOptions(
            name='soporte',
            options={'managed': False, 'verbose_name': 'Ticket de Soporte', 'verbose_name_plural': 'Tickets de Soporte'},
        ),
        migrations.AlterModelOptions(
            name='soportemensaje',
            options={'managed': False, 'verbose_name': 'Mensaje de Soporte', 'verbose_name_plural': 'Mensajes de Soporte'},
        ),
    ]
