# Generated by Django 6.0.4 on 2026-04-23 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='soporte',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_soporte', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='soportemensaje',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_soporte', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='soportemensaje',
            name='soporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='support.soporte'),
        ),
        migrations.AddIndex(
            model_name='soporte',
            index=models.Index(fields=['estado_soporte', 'fecha_creacion'], name='soporte_estado__2aa3d4_idx'),
        ),
    ]
